### ISSUE TITLE
Electra for Hungarian language 

### ISSUE THREAD

**Issue by Mohammed20201991** [szegedai/byte-offset-tokenizer#1]
I am trying to use the Elctta model for the Hungarian language but I have this issue when I am using it on collab 
![image](https://user-images.githubusercontent.com/59222637/198403311-501bf147-75d5-49c6-9270-e847bf287b5a.png)

and her it is my snapped code 
```
from typing_extensions import Literal
from transformers import VisionEncoderDecoderModel , AutoModel

decoder_model = AutoModel.from_pretrained("SzegedAI/charmen-electra", trust_remote_code=True)
```

**Comment by ficstamas** [comment]
Hey, sorry about the late response. I didn't notice that you opened an issue (and github didn't send a notification either because it is under szegedai).

If it is still relevant, then the problem is really simple. [Literal](https://peps.python.org/pep-0586/) is a Python 3.8 feature, and your notebook uses a Python 3.7 interpreter. It should work nowadays!
